package web.api.model;
// Generated Nov 23, 2020 7:39:35 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Movies generated by hbm2java
 */
public class Movies  implements java.io.Serializable {


     private int id;
     private String title;
     private String imagelink;
     private String link;
     private String description;
     private Boolean published;
     private Date createdAt;
     private Date updatedAt;

    public Movies() {
    }

	
    public Movies(int id, Date createdAt, Date updatedAt) {
        this.id = id;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
    public Movies(int id, String title, String imagelink, String link, String description, Boolean published, Date createdAt, Date updatedAt) {
       this.id = id;
       this.title = title;
       this.imagelink = imagelink;
       this.link = link;
       this.description = description;
       this.published = published;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getImagelink() {
        return this.imagelink;
    }
    
    public void setImagelink(String imagelink) {
        this.imagelink = imagelink;
    }
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Boolean getPublished() {
        return this.published;
    }
    
    public void setPublished(Boolean published) {
        this.published = published;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }




}


